name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the GitHub repository to the machine
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm install
    - name: Run the FE
      run: npm start &
    - name: Run the BE
      run: npm server &
    - name: Install browsers
      run: npx playwright install
    - name: Run tests
      run: npm test

  deploy-be:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID_BE }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}

  deploy-fe:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID_FE }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
